### ISSUE TITLE
LoadException: Root value already specified

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/ignite#8]
So far, each `FXMLView` injects the same `FXMLRootProvider` object, which is annotated as Singleton, so it uses the same `FXMLLoader` object.

When there are more than one FXML file, this causes:

```
Caused by: javafx.fxml.LoadException: Root value already specified.
        at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2703)
        at javafx.fxml/javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2856)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2805)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2634)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2532)
        at com.gluonhq.ignite.micronaut.FXMLRootProvider.getRootByClass(FXMLRootProvider.java:59)
 
```
which prevents the use of more than one FXMLView per application.

As a quick fix, removing the `@Singleton` annotation from `FXMLRootProvider` seems to solve the problem. 
Alternatively, `loader` can be replaced with `ctx.getBean(FXMLLoader.class)`.

**Comment by eugener** [comment]
Good solution may be to inject FXMLLoaderFactory and get a loader from it dynamically… because loader needs that controller factory set
```
 @Inject FXMLLoaderFactory loaderFactory;
```
and then
```
loaderFactory.getLoader().load(...)
```
all this within `FXMLRootProvider`
